application: helloworld
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: static/index.html
  upload: static/index\.html

- url: /(.*)\.html
  static_files: static/\1.html
  upload: static/index\.html

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /ajax
  script: ajaxhandler.py

